from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


# ══════════════════════════════════════════════════════════════
# USER
# ══════════════════════════════════════════════════════════════

class UserManager(BaseUserManager):
    """Custom manager so we can create users with email instead of username."""

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email is required.")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_admin", True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom user model.
    - email is the login field (no username).
    - Roles: is_admin (staff) / is_user (regular).
    - is_blocked lets admins lock out a user without deleting them.
    """

    email      = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name  = models.CharField(max_length=50, blank=True)
    avatar     = models.ImageField(upload_to="avatars/", null=True, blank=True)

    # Roles
    is_admin = models.BooleanField(default=False)  # admin dashboard access
    is_user  = models.BooleanField(default=True)   # regular user

    # Status
    is_active  = models.BooleanField(default=True)
    is_blocked = models.BooleanField(default=False, db_index=True)  # admin can block
    is_staff   = models.BooleanField(default=False)  # Django admin access

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD  = "email"
    REQUIRED_FIELDS = []  # email + password are enough

    class Meta:
        verbose_name = "User"
        ordering = ["-created_at"]

    def __str__(self):
        return self.email

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}".strip() or self.email


# ══════════════════════════════════════════════════════════════
# EMAIL CAMPAIGN
# ══════════════════════════════════════════════════════════════

class EmailCampaign(models.Model):
    """
    Represents a marketing campaign a user is running.
    Example: "Black Friday Sale", "SaaS Product Launch Q1".
    """

    class Status(models.TextChoices):
        DRAFT    = "draft",    "Draft"
        ACTIVE   = "active",   "Active"
        ARCHIVED = "archived", "Archived"

    class Industry(models.TextChoices):
        ECOMMERCE  = "ecommerce",   "E-commerce"
        SAAS       = "saas",        "SaaS"
        FINANCE    = "finance",     "Finance"
        HEALTHCARE = "healthcare",  "Healthcare"
        EDUCATION  = "education",   "Education"
        OTHER      = "other",       "Other"

    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name="campaigns")
    title           = models.CharField(max_length=120)
    description     = models.TextField(blank=True, help_text="What is this campaign about?")
    industry        = models.CharField(max_length=20, choices=Industry.choices, default=Industry.OTHER)
    target_audience = models.CharField(max_length=200, blank=True, help_text="e.g. Women 25-40 interested in fashion")
    status          = models.CharField(max_length=10, choices=Status.choices, default=Status.DRAFT, db_index=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Email Campaign"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} ({self.owner.email})"


# ══════════════════════════════════════════════════════════════
# SUBJECT LINE
# ══════════════════════════════════════════════════════════════

class SubjectLine(models.Model):
    """
    A single email subject line belonging to a campaign.
    Can be written manually or generated by the AI.
    """

    class Tone(models.TextChoices):
        PROFESSIONAL = "professional", "Professional"
        CASUAL       = "casual",       "Casual"
        URGENT       = "urgent",       "Urgent"
        CURIOUS      = "curious",      "Curious"
        FUNNY        = "funny",        "Funny"

    campaign         = models.ForeignKey(EmailCampaign, on_delete=models.CASCADE, related_name="subject_lines")
    text             = models.CharField(max_length=150, help_text="The subject line text (max 150 chars)")
    tone             = models.CharField(max_length=15, choices=Tone.choices, default=Tone.PROFESSIONAL)
    is_ai_generated  = models.BooleanField(default=False, db_index=True)
    performance_score = models.PositiveSmallIntegerField(
        null=True, blank=True,
        help_text="Optional score 0-100 from A/B testing"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Subject Line"
        ordering = ["-created_at"]

    def __str__(self):
        tag = "🤖" if self.is_ai_generated else "✍"
        return f"{tag} {self.text[:60]}"


# ══════════════════════════════════════════════════════════════
# AI CHAT SESSION & MESSAGES
# ══════════════════════════════════════════════════════════════

class ChatSession(models.Model):
    """
    A conversation thread between a user and the AI.
    Optionally linked to a specific campaign for context.
    """

    user     = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chat_sessions")
    campaign = models.ForeignKey(
        EmailCampaign,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="chat_sessions",
        help_text="Optional: link this session to a campaign"
    )
    title      = models.CharField(max_length=120, blank=True, help_text="Auto-generated or user-defined title")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Chat Session"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Session '{self.title or self.id}' — {self.user.email}"


class ChatMessage(models.Model):
    """
    A single message inside a ChatSession.
    role = 'user'      → sent by the human
    role = 'assistant' → AI response (stored as Markdown)
    """

    class Role(models.TextChoices):
        USER      = "user",      "User"
        ASSISTANT = "assistant", "Assistant"

    session    = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name="messages")
    role       = models.CharField(max_length=10, choices=Role.choices)
    content    = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Chat Message"
        ordering = ["created_at"]  # chronological order

    def __str__(self):
        preview = self.content[:50]
        return f"[{self.role.upper()}] {preview}"
